# Generated by Django 5.2.13 on 2026-07-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Now',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Currently', max_length=100)),
                ('project', models.CharField(max_length=200)),
                ('learning', models.CharField(max_length=200)),
                ('reading', models.CharField(blank=True, max_length=200)),
                ('drinking', models.CharField(default='Coffee ☕', max_length=100)),
                ('status', models.CharField(default='Available for Work', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
